import Head from "next/head";
import Landing from "../modules/landing";
import { NextPageWithLayout } from "../types/next-page";

const Home: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Multivurse - Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing/>
    </>
  );
};

Home.layout = "auth";

export default Home;
