import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";
import Button from "../components/Button";
import Input from "../components/Input";
import Alert from "../components/Alert";
import {
  InstagramLogo,
  PencilCircle,
  TwitterLogo,
  WarningCircle,
  YoutubeLogo,
} from "phosphor-react";
import { SubmitHandler, useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import { MouseEvent, useState } from "react";
import Label from "../components/Label";
import { useRouter } from "next/router";
import { useMediaQuery } from "react-responsive";
import { signOut } from "firebase/auth";
import { auth } from "../firebaseConfig";
import Image from "next/image";
import CircularButton from "../components/Circular";
import { NextPageWithLayout } from "../types/next-page";
import SocialsPage from "../modules/socialsPage";
import BillingPage from "../modules/billingPage";
import PublicPage from "../modules/publicPage";

const Public: NextPageWithLayout = () => {
  const [btn, setBtn] = useState(true);

  return (
    <>
      <Head>
        <title>TPC - Public</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-full w-ful justify-start items-start">
        <PublicPage edit={btn}  />
      </div>
    </>
  );
}

Public.layout = "auth";
Public.background = "default";

export default Public;