import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";
import Button from "../components/Button";
import Input from "../components/Input";
import Alert from "../components/Alert";
import { CheckCircle, WarningCircle } from "phosphor-react";
import { SubmitHandler, useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import { useState } from "react";
import Label from "../components/Label";
import { useRouter } from "next/router";
import { useMediaQuery } from "react-responsive";
import { createUserWithEmailAndPassword } from "firebase/auth";
import { auth } from "../firebaseConfig";

const passwordRequirements = [
  {
    label: "Upper and lower case",
    pattern: /(?=.*[a-z])(?=.*[A-Z])/,
  },
  {
    label: "Numbers",
    pattern: /(?=.*\d)/,
  },
  {
    label: "Special characters (ex: @$!%*?&.^#)",
    pattern: /(?=.*[@$!%*?&.^#])/,
  },
  {
    label: "8+ characters",
    pattern: /.{8,}/,
  },
];

const PASSWORD_PATTERN = new RegExp(
  `^${passwordRequirements
    .map((requirement) => requirement.pattern.source)
    .join("")}$`
);

export type FormValues = {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
};

const schema = yup
  .object({
    email: yup.string().email("Must be a valid email").required("Required"),
    firstName: yup.string().required("Required"),
    lastName: yup.string().required("Required"),
    password: yup
      .string()
      .matches(PASSWORD_PATTERN, "Invalid Password")
      .required("Required"),
  })
  .required();

export default function Register() {
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const {
    register,
    handleSubmit,
    watch,
    formState: { isValid, errors },
  } = useForm<yup.InferType<typeof schema>>({
    resolver: yupResolver(schema),
    mode: "onChange",
  });
  const router = useRouter();
  const onSubmit: SubmitHandler<FormValues> = (data) => {
    setLoading(true);
    createUserWithEmailAndPassword(auth, data.email, data.password)
      .then(async(res) => {
        setLoading(false);
        console.log(res);
        await router.replace("/home");
      })
      .catch((err) => {
        console.log(err);
        setError("Your email and/or password are incorrect.");
      });
  };

  const isDesktopOrLaptop = useMediaQuery({
    query: "(min-width: 1000px)",
  });
  const isTabletOrMobile = useMediaQuery({ query: "(max-width: 1000px)" });
  const passwordField = watch("password");

  return (
    <>
      <Head>
        <title>TPC - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card
          className={`h-9/12 roundedXl flex flex-col justify-center items-center bg-white ${
            isDesktopOrLaptop
              ? "w-6/12"
              : isTabletOrMobile
              ? "w-full"
              : "w-6/12"
          }`}
        >
          <h1 className="text-black text-xl font-bold mt-4">TPC</h1>
          <span className="h-0.5 mt-2 w-full bg-gray-900"></span>
          <div className="px-3">
            <div className="container mx-auto max-w-md">
              <div className="my-6">
                <div
                  className={error ? "block bg-gray-900 rounded-lg" : "hidden"}
                >
                  <Alert variant="error">
                    <div className="flex flex-row">
                      <div className="flex-shrink-0 text-error">
                        <WarningCircle size={24} weight="bold" color="#fff" />
                      </div>
                      <div className="text-white ml-3">{error}</div>
                    </div>
                  </Alert>
                </div>
              </div>
              <form method="post" onSubmit={handleSubmit(onSubmit)}>
                <div className="mt-9">
                  <div>
                    <Label htmlFor="firstName">First Name</Label>
                    <Input
                      id="firstName"
                      isInvalid={!!errors.firstName}
                      {...register("firstName")}
                    />
                  </div>
                  <div>
                    <Label htmlFor="lastName">Last Name</Label>
                    <Input
                      id="lastName"
                      isInvalid={!!errors.lastName}
                      {...register("lastName")}
                    />
                  </div>

                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    autoComplete="email"
                    {...register("email")}
                  />
                </div>
                <div className="mt-1 mb-2">
                  <div className="flex flex-row justify-between">
                    <Label htmlFor="password">Password</Label>
                    <a
                      className="text-sm text-primary cursor-pointer"
                      onClick={() => setShowPassword(!showPassword)}
                    >
                      {showPassword ? "Hide" : "Show"}
                    </a>
                  </div>
                  <div className="flex items-center relative mt-3">
                    <Input
                      id="password"
                      type={showPassword ? "text" : "password"}
                      autoComplete="current-password"
                      {...register("password")}
                    />
                    {passwordField?.match(PASSWORD_PATTERN) && (
                      <CheckCircle
                        size={24}
                        weight="fill"
                        color="currentColor"
                        className="text-primary absolute right-2"
                      />
                    )}
                  </div>
                </div>

                <span className="text-sm text-gray-900 ">
                  Please fill the forms to activate registration
                </span>

                <div className="mt-4">
                  <Button
                    type="submit"
                    variant="primary"
                    className="w-full pt-2 mt-2 mb-2 text-md text-white bg-gray-900 hover:bg-gray-800 disabled:bg-gray-400 disabled:pointer-events-none px-4 py-2"
                    disabled={!isValid}
                    loading={loading}
                  >
                    Register
                  </Button>
                </div>
                <div className="mt-2">
                  <Button
                    type="button"
                    variant="primary"
                    className="w-full pt-2 mb-2 text-md text-gray-900 hover:text-gray-500 bg-transparent px-4 py-2"
                    onClick={() => router.push("/")}
                  >
                    Sign In
                  </Button>
                </div>
              </form>
            </div>
          </div>
        </Card>
      </main>
    </>
  );
}
