import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";
import Button from "../components/Button";
import Input from "../components/Input";
import Alert from "../components/Alert";
import {
  InstagramLogo,
  TwitterLogo,
  WarningCircle,
  YoutubeLogo,
} from "phosphor-react";
import { SubmitHandler, useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import { MouseEvent, useState } from "react";
import Label from "../components/Label";
import { useRouter } from "next/router";
import { useMediaQuery } from "react-responsive";
import { signOut } from "firebase/auth";
import { auth } from "../firebaseConfig";
import Image from "next/image";
import CircularButton from "../components/Circular";
import { NextPageWithLayout } from "../types/next-page";

const Verification: NextPageWithLayout = () => {
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const isDesktopOrLaptop = useMediaQuery({
    query: "(min-width: 1000px)",
  });
  const isTabletOrMobile = useMediaQuery({ query: "(max-width: 800px)" });

  return (
    <>
      <Head>
        <title>TPC - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full bg-gray-50 justify-center items-center rounded-3xl mt-5">
        Verification
      </main>
    </>
  );
}

Verification.layout = "main";
Verification.background = "default";

export default Verification;